version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # This will expose port 80 of the container to port 4200 on the VM (optional)
    container_name: angular-app
