version: '3.8'

services:
  angular-app:
    container_name: angular-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["ng", "serve", "--host", "0.0.0.0"]
