version: '3.8'

services:
  angular-app:
    container_name: angular-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Le port 80 est utilisé pour Nginx
    volumes:
      - .:/usr/src/app  # Montez les fichiers de votre projet pour éviter de reconstruire à chaque modification
    restart: always
