version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"  # Map port 8082 on the host to port 80 in the container
    container_name: nginx-angular-app
