version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:80"  # Map port 7070 on the host to port 80 in the container
    container_name: angular-app
